services:
  php-fpm:
    image: ghcr.io/fredchess/hidima-backend:latest
    pull_policy: always
    restart: unless-stopped
    volumes:
      - storage-data:/var/www/storage
    env_file:
      - .env
    networks:
      - hidima
      - dokploy-network
    healthcheck:
      test: ["CMD-SHELL", "pidof php-fpm || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
      args:
        GITHUB_REPOSITORY: fredchess/hidima-backend
        IMAGE_TAG: ${IMAGE_TAG:-latest}
      pull: true
    restart: unless-stopped
    depends_on:
      - php-fpm
    volumes_from:
      - php-fpm:ro
    networks:
      - hidima

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - hidima
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  storage-data:

networks:
  hidima:
  dokploy-network:
    external: true
